### ISSUE TITLE
Plugin Lib missing

### ISSUE THREAD

**Issue by Linuxpleb** [catsout/wallpaper-engine-kde-plugin#113]
I am missing my plugin lib and I am unsure what I did wrong I know its my fault but I need help figuring it out all requirements are met except the plugin lib. It displays wallpapers but it says for some of them I need the plugin lib to run. only error during install was for the meta data json. Thank you for your time!

**Kde version**
- Kde: 5.20.5
- Qt: 5.15.2
- OS: MXahs xfce 5.15

**Additional context**

**Comment by chcoomilk** [comment]
I had the same issue because I downloaded and installed the plugin directly from the plasma plugin desktop without installing the folderlistmodel (`sudo apt install qml-module-qt-labs-folderlistmodel`). If that does not work, try building it from the source.

This fix might not work for you since I use Debian 11 and I don't know much about xfce OS..??

**Comment by catsout** [comment]
Please go https://github.com/catsout/wallpaper-engine-kde-plugin/issues/133 to continue.
