### ISSUE TITLE
extra dependency vulkan-driver needed, otherwise scene wallpapers don't work

### ISSUE THREAD

**Issue by LeoJhonSong** [catsout/wallpaper-engine-kde-plugin#147]
**Describe the bug**<br/>
Hi, Thanks for the wonderful work! As I am on Manjaro Linux, I installed all dependencies for Arch listed [here](https://github.com/catsout/wallpaper-engine-kde-plugin#dependencies) in the README, I built and installed it with no errors. But I could only apply video wallpapers (I did not check image papers) when **with Intel graphics card only**, scene wallpapers were not  dispalying correctly: only black screen there. However, when running my X server **on Nvidia graphcis card** everything works perfectly :joy:  With the [test code in #137](https://github.com/catsout/wallpaper-engine-kde-plugin/issues/137#issuecomment-1074908532), **on InteI graphics cards**, I got:

```shell
INFO main looper started
INFO render looper started
INFO set swapchain image size: 1280x720
INFO source: /run/media/Windows/Users/LeoJhon/Softwares/Steam/steamapps/workshop/content/431960/1604548597/scene.pkg
ERROR Instance.cpp:209 VkResult is " ErrorIncompatibleDriver "
sceneviewer: /home/leo/local/wallpaper-engine-kde-plugin/src/backend_scene/wallpaper/Vulkan/Instance.cpp:209: static bool wallpaper::vulkan::Instance::Create(wallpaper::vulkan::Instance&, Span<wallpaper::vulkan::Extension>, Span<wallpaper::vulkan::Extension>): Assertion `res == vk::Result::eSuccess' failed.
[1]    6633 IOT instruction (core dumped)  ./sceneviewer
```

After searching I found out it was because I only have Vulkan driver intalled for my Nvidia graphics card, but not for the Interl graphics card. Here is the command to list which Vulkan drivers have you installed: `ls /usr/share/vulkan/icd.d/`.

So, after executing `sudo  pacman -S vulkan-intel`, everything works perfectly for me even on Interl graphics card onyl now! I am good now and I am just here to provide the information in case someone came up with the same situation. Finally, I want to thank again to this grate project which allows me to gain so many beautiful wallpapers!

For you information, [here](https://wiki.archlinux.org/title/Vulkan#Installation) is the ArchWiki for Vulkan, which tells you which packages to install depending on the graphics cards you have.

**System Information**
- Kde: Plasma 5.24.3
- OS: Manjaro Linux x86_64
- Kernel: 5.15.28-1-MANJARO
- Installation Source: git

**Comment by Zukiyomi** [comment]
Ohhh your advice helped me solve the problem on my Arch, thank you very much!

**Comment by l27001** [comment]
_Before you read this I want to apologize for my poor English and the use of a translator_

On Arch Linux with Vega 7 (Ryzen 5600G) I have same problem, but `amdvlk` driver (was installed with another package) did not solve the problem.
I tried install `vulkan-radeon` driver, but it didn't work. Because it must be selected for use by default (or only for this plugin, but I have not found a way to do this).

The driver's selection is done by setting the environment variable `VK_ICD_FILENAMES` with path(s) to the driver files in the directory `/usr/share/vulkan/icd.d/`

Example from archwiki:
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json`

I set this environment variable globally by adding to `/etc/profile` the line:
`export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json`

After that everything works as it should

**Comment by ETCHKILI** [comment]
@l27001 thanks a lot! I'm suffering from this issue with an amd gpu.

**Comment by poncho-ajmv** [comment]
Thanks a lot, work for me
