### ISSUE TITLE
Got weird color in video wallpaper with QtMultimedia backend

### ISSUE THREAD

**Issue by YidaozhanYa** [catsout/wallpaper-engine-kde-plugin#155]
**Workshop link**<br/>
https://steamcommunity.com/sharedfiles/filedetails/?id=2239430876

**System Information**
- Kde: 5.24.4
- Qt: 5.15.3
- OS: ArchLinux
- Installation Source: git

**Additional context**<br/>

![image](https://user-images.githubusercontent.com/73830635/162748240-481a4fed-cfa9-4543-abf8-ba7835a4f353.png)
![image](https://user-images.githubusercontent.com/73830635/162748279-3e910e00-9d58-4fd3-906d-526d898b87ac.png)

**Comment by AngelSherry** [comment]
Today, I also had the same issue on openSUSE Tumbleweed.
But I found that it caused by installing gstreamer-plugins-vaapi, whitch will make the color of videos get weird.

After installed gstreamer-plugins-vaapi:
![Screenshot_20220605_002810](https://user-images.githubusercontent.com/53128145/172016746-b6006185-feb8-4944-9c7a-8d534882c03b.png)

After unstalled gstreamer-plugins-vaapi:
![Screenshot_20220605_003223](https://user-images.githubusercontent.com/53128145/172016765-fe6303bc-7780-459b-b7ea-aba694448c60.png)

I don't know why gstreamer-plugins-vaapi will cause this issue, but you can have a try on you distro.

**Comment by YidaozhanYa** [comment]
After uninstalling gstreamer-vaapi, the colors became normal, but the video pauses forever after a few seconds of playback.
