### ISSUE TITLE
Plugin Lib not found on ArchLinux

### ISSUE THREAD

**Issue by AnaxMorden** [catsout/wallpaper-engine-kde-plugin#188]
**Describe the bug**<br/>
On Archlinux it wont find Plugin lib (even if i installed it with pip)

**Workshop link**<br/>
[1894838794](https://steamcommunity.com/sharedfiles/filedetails/?id=1894838794)

**System Information**
- Kde: 5.24-1
- Qt: 5.15.4+kde+r168-1
- OS: ArchLinux
- Installation Source: KDE Plugins

**Additional context**<br/>
![grafik](https://user-images.githubusercontent.com/79524821/173914552-2157e9fb-c74c-4b7a-8b75-47889914f82c.png)

**Comment by Extrallian** [comment]
same here, I've had this problem off and on

**Comment by catsout** [comment]
`git pull`
compile and install again.

**Comment by DoomSlinger** [comment]
I'm having this issue too. The program was completely fine until I installed some arch updates today. I had just updated maybe a week ago at most (more like 4 or 5 days ago) and it was fine so a recent update to arch caused the issue. I tried rolling back but it just threw an error (one of the updates was not letting me roll it back and it was breaking the whole thing). The update also broke the scroll bar for the wallpaper selection menu, swapping the location of the wallpaper description and list scroll wheels.

**Comment by davigamer987** [comment]
Same issue here, still can't find a fix

**Comment by davigamer987** [comment]
Logs from running kstart5 plasmashell:

qml: ---check lib 'com.github.catsout.wallpaperEngineKde 1.2' failed---
qml: Error: Qt.createQmlObject(): failed to create object: 
    file:///home/davi/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/contents/ui/inline:1:1: plugin cannot be loaded for module "com.github.catsout.wallpaperEngineKde": Cannot load library /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so: (libSvtAv1Enc.so.0: cannot open shared object file: No such file or directory)
qml: load backend: backend/QtMultimedia.qml

**Comment by AnaxMorden** [comment]
Solved the issue by Compiling everything from source

Plugin Lib is now detected by the Plugin

**Comment by 222b222b** [comment]
Solved the issue by updating the kernel and compiling everything from source.

**Comment by davigamer987** [comment]
if you don't want to build everything from source you can do this. Run sudo ln /usr/lib/SvtAv1Enc.so.1 /usr/lib/libSvtAv1Enc.so.0 and sudo ln /usr/lib/libsrt.so /usr/lib/libsrt.so.1.4  (This also fixed ksysguard for me)

**Comment by DoomSlinger** [comment]
Unfortunately, neither of the previously mentioned options worked for me. I've always used the manually compiled version rather than the store version, and when running the two commands, it didn't work for me at all, the first command threw and error that said that file doesn't exist, and the second didn't have any effect.

**Comment by Smart-Helper** [comment]
@DoomSlinger 
I'm on GarudaLinux (so basically Arch)

Maybe you can help me out since you fixed yours. I have mpv and ffmpeg installed. But i cannot change from QtMultimedia to mpv - there is no other option. Did you have to do something to fix that? Because my wallpapers also get stuck at looping sometimes. They CAN loop, but sometimes they just stop.

**Comment by AnaxMorden** [comment]
Fixes should be all in comments
