### ISSUE TITLE
plugin lib not installed

### ISSUE THREAD

**Issue by Luminous-Journey** [catsout/wallpaper-engine-kde-plugin#383]
**Describe the bug**<br/>
when using the self build method for kde6, the plugin lib for displaying the mpv, does not install or somthing and it does not show up as installed on the background about page

**System Information**
- Kde: 6.02
- Qt: 6
- OS: Arch
- Installation Source: git self build for qt6
- Wallpaper Engine version: 2.4.82

**Additional context**<br/>
Add any other context about the problem here. [e.g. screenshots/logs]
![background manager](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/77587691/2ad4da57-8844-441e-8456-23de2e7b91e9)
![desktop](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/77587691/6a136ebe-2b86-490c-b403-58fc02da3b83)

**Comment by Luminous-Journey** [comment]
Looking at the readme it appears that mpv or something is required but in the settings all i have is Qtmultimedia?
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/77587691/26a5cb18-9d45-4e06-9340-2c7c410f1316)

**Comment by AngelSherry** [comment]
I suggest do a clean install before building it.

```
rm -rf ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde
rm -rf ~/.local/share/kpackage/generic/com.github.casout.wallpaperEngineKde/
sudo rm -rf /usr/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde/
sudo rm -f /usr/lib/qt6/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
sudo rm -rf /usr/lib/qt6/qml/com/github/catsout/wallpaperEngineKde/qmldir
```

The installation on README is not only compiled on system-wide, but also using kpackagetool6 to install to user directory. Therefore you may get two inconsistent version if you don't delete the files on user directory and system-wide..

I prefer to install it to system-wide instead of using kpackagetool6 to make it more complicated to maintain.

```
cmake -B build -S . \
    -DCMAKE_BUILD_TYPE=Release \
    -DQT_MAJOR_VERSION=6 \
    -DUSE_PLASMAPKG=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DSPIRV_REFLECT_STATIC_LIB=ON \
    -DBUILD_QML=ON

cmake --build build

cmake --install build
```
And don't forget to install mpv and vulkan-header for building scene. It can be compiled without them, but you won't be able to use scene

![圖片](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/53128145/c92d9bf6-1eee-4064-b0cc-774105d8f563)

.
![圖片](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/53128145/f80986f5-5aaa-44f7-a2a4-2d7cff7607c4)

**Comment by ArmandoTeranCastillo** [comment]
@AngelSherry  Can you bring me your full build? I have the same problem

**Comment by ArmandoTeranCastillo** [comment]
@AngelSherry  Omg, it works!! Thank you so much

**Comment by Luminous-Journey** [comment]
Tysm

**Comment by xvers** [comment]
Thanks very much, this works for me! I'm using Nobara, and works like a charm! 🥇

**Comment by Pablito3234** [comment]
For whoever had my same problem when trying to apply @AngelSherry solution. Everything worked except when trying to build with CMake, I turned out that one of the packages you also need to update is kf6-kcoreaddons, in Fedora you can do it with ``sudo dnf update kf6-kcoreaddons`` then just proceed with the building

**Comment by OkeDok1e** [comment]
I am on nobara 40 and i had CMake issues when i tried to install the build but it said Dependencies resolved.
Nothing to do.
Complete!

**Comment by cagla-su** [comment]
@AngelSherry it's been more than a year but still us Fedora users should follow the steps you added in order to make the plugin run on Fedora Plasma. Thank you so much <3
